// Corpus Wiktionnaire — CC-BY-SA 4.0 — Source : fr.wiktionary.org
// 100 entrées — 5 lettres

const DICTIONNAIRE = {
  A: [
    { als: "Aarau", fr: "Ville du canton d’Argovie en Suisse" },
    { als: "Actinium", fr: "Actinium" },
    { als: "Adrastea", fr: "Adrastée" },
    { als: "Aegir", fr: "Ægir (satellite naturel de Saturne)" },
    { als: "Afghanistan", fr: "Afghanistan (pays asiatique)" },
    { als: "Aisne", fr: "Aisne (département français)" },
    { als: "Albanie", fr: "Albanie (pays européen)" },
    { als: "Alpen", fr: "Alpes (chaîne de montagnes)" },
    { als: "Alphabet", fr: "Alphabet" },
    { als: "Altertum", fr: "Antiquité" },
    { als: "Aluminium", fr: "Aluminium" },
    { als: "Americium", fr: "Américium" },
    { als: "Antimon", fr: "Antimoine" },
    { als: "Apfig", fr: "Epfig, commune française, située dans le département du Bas-Rhin" },
    { als: "Arelse", fr: "Ernolsheim-Bruche, commune française, située dans le département du Bas-Rhin" },
    { als: "Argon", fr: "Argon" },
    { als: "Arische", fr: "Ergersheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Armenie", fr: "Arménie (pays du Caucase)" },
    { als: "Arsen", fr: "Arsenic" },
    { als: "Aschöi", fr: "Eschau, commune française, située dans le département du Bas-Rhin" },
    { als: "Aserbaidschan", fr: "Azerbaïdjan, pays du Caucase" },
    { als: "Astat", fr: "Astate" },
    { als: "Attedorf", fr: "Ettendorf, commune française, située dans le département du Bas-Rhin" },
    { als: "Auenem", fr: "Auenheim, commune française, située dans le département du Bas-Rhin" },
  ],
  B: [
    { als: "Banfald", fr: "Benfeld, commune française, située dans le département du Bas-Rhin" },
    { als: "Banze", fr: "Bernolsheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Barembach", fr: "Barembach, commune française, située dans le département du Bas-Rhin" },
    { als: "Baribiete", fr: "Bergbieten, commune française, située dans le département du Bas-Rhin" },
    { als: "Barium", fr: "Baryum" },
    { als: "Barschem", fr: "Berstheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Barstett", fr: "Berstett, commune française, située dans le département du Bas-Rhin" },
    { als: "Basel", fr: "Bâle, en Suisse" },
    { als: "Bassemberg", fr: "Bassemberg, commune française, située dans le département du Bas-Rhin" },
    { als: "Batschdorf", fr: "Betschdorf, commune française, située dans le département du Bas-Rhin" },
    { als: "Batschwiller", fr: "Bernardswiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Bayern", fr: "Bavière" },
    { als: "Befoss", fr: "Bellefosse, commune française, située dans le département du Bas-Rhin" },
    { als: "Belgien", fr: "Belgique, pays d'Europe" },
    { als: "Belgrad", fr: "Belgrade, capitale de la Serbie" },
    { als: "Berkelium", fr: "Berkélium" },
    { als: "Berlin", fr: "Berlin (ville allemande)" },
    { als: "Bersch", fr: "Bœrsch, commune française, située dans le département du Bas-Rhin" },
    { als: "Beryllium", fr: "Béryllium" },
    { als: "Bettwiller", fr: "Bettwiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Biese", fr: "Bœsenbiesen, commune française, située dans le département du Bas-Rhin" },
    { als: "Bietle", fr: "Bietlenheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Bihl", fr: "Buhl, commune française, située dans le département du Bas-Rhin" },
    { als: "Bissert", fr: "Bissert, commune française, située dans le département du Bas-Rhin" },
    { als: "Blaase", fr: "Blæsheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Blei", fr: "Plomb" },
    { als: "Bleschwiller", fr: "Blienschwiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Bodensee", fr: "Lac de Constance" },
    { als: "Bohrium", fr: "Bohrium" },
    { als: "Bolsene", fr: "Bolsenheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Boofze", fr: "Boofzheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Bor", fr: "Bore" },
    { als: "Bosnien-Herzegowina", fr: "Bosnie-Herzégovine (pays d’Europe)" },
    { als: "Bossedorf", fr: "Bossendorf, commune française, située dans le département du Bas-Rhin" },
    { als: "Bosselshüse", fr: "Bosselshausen, commune française, située dans le département du Bas-Rhin" },
    { als: "Braitebàch", fr: "Breitenbach, commune française, située dans le département du Bas-Rhin" },
    { als: "Bàldene", fr: "Baldenheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Bàlwere", fr: "Balbronn, commune française, située dans le département du Bas-Rhin" },
    { als: "Bàrr", fr: "Barr, commune française, située dans le département du Bas-Rhin" },
    { als: "Bàtzedorf", fr: "Batzendorf, commune française, située dans le département du Bas-Rhin" },
    { als: "Bänem", fr: "Beinheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Bäredorf", fr: "Baerendorf, commune française, située dans le département du Bas-Rhin" },
    { als: "Bärich", fr: "Berg, commune française, située dans le département du Bas-Rhin" },
    { als: "Bémont", fr: "Belmont, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìlse", fr: "Bilwisheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìndre", fr: "Bindernheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìrikewàld", fr: "Birkenwald, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìsche", fr: "Bischheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìscholz", fr: "Bischholtz, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìscht", fr: "Bust, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìschwiller", fr: "Bischwiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìtschoffe", fr: "Bitschhoffen, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìtte", fr: "Butten, commune française, située dans le département du Bas-Rhin" },
    { als: "Bìwelse", fr: "Biblisheim, commune française, située dans le département du Bas-Rhin" },
  ],
  À: [
    { als: "Àbgenn", fr: "Abandon" },
    { als: "Àchene", fr: "Achenheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Àdàmswiller", fr: "Adamswiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Àldorf", fr: "Altorf, commune française, située dans le département du Bas-Rhin" },
    { als: "Àllewiller", fr: "Allenwiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Àltackedorf", fr: "Alteckendorf, commune française, située dans le département du Bas-Rhin" },
    { als: "Àltene", fr: "Altenheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Àltwiller", fr: "Altwiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Àndlöi", fr: "Andlau, commune française, située dans le département du Bas-Rhin" },
    { als: "Àngwiller", fr: "Engwiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Ànze", fr: "Entzheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Àrtelse", fr: "Artolsheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Àschbàch", fr: "Aschbach, commune française, située dans le département du Bas-Rhin" },
    { als: "Àsswiller", fr: "Asswiller, commune française, située dans le département du Bas-Rhin" },
    { als: "Àtzne", fr: "Hohatzenheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Àvelse", fr: "Avolsheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Àwerbach", fr: "Eberbach-Seltz, commune française, située dans le département du Bas-Rhin" },
    { als: "Àwersche", fr: "Ebersheim, commune française, située dans le département du Bas-Rhin" },
    { als: "Àwerschmìnster", fr: "Ebersmunster, commune française, située dans le département du Bas-Rhin" },
  ],
  Ã: [
    { als: "ãn", fr: "Allumé" },
  ],
  Ä: [
    { als: "Ägypten", fr: "Égypte (pays africain)" },
    { als: "Äschhoffe", fr: "Eichhoffen, commune française, située dans le département du Bas-Rhin" },
  ],
};

const LETTERS_WITH_ENTRIES = Object.keys(DICTIONNAIRE);
const ALL_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');